### ISSUE TITLE
Header file location changed

### ISSUE THREAD

**Issue by cocreature** [abooij/haskell-xkbcommon#6]
It looks like in one of the latest linux releases (I think it is [this commit](https://github.com/torvalds/linux/commit/f902dd893427eade90f7eaf858e5ff8b150a5a12#diff-7f263bfcb23858e82a9a42a27cc387db)) the key codes are now in `linux/input-event-codes.h`. I guess the proper solution to this would be to first check for this new header and fall back to the old one.

I am sadly busy during the next weeks so I don’t have time to make a PR.

**Comment by abooij** [comment]
Doesn't `linux/input.h` include this new file?

**Comment by cocreature** [comment]
Oh right, I missed that. However it looks the symtab returned by cpphs is missing the defines from that include. I’ll take a look when I get around to it.

**Comment by cocreature** [comment]
Alright, `macroPassReturningSymTab` just ignores `#include`. It is necessary to call `cppIfdef` beforehand to handle `#include` and `#ifdef`. It might make sense to disable warnings for that call to avoid errors for other includes that we are not interested in.

**Comment by abooij** [comment]
Okay but then we have to be a bit smarter because `cppIfDef` needs to be fed a search path, which we haven't computed. The purpose of the `readHeader` trick is exactly to avoid dealing with finding the right search path (instead using the `cpp` system tool to deal with that).

Suggestions are welcome.

**Comment by cocreature** [comment]
No I tried it you can use an empty search path and it will search in the current directory which works for the linux headers. You get warnings for other headers but you could just turn off warnings.

**Comment by cocreature** [comment]
I think calling `echo | cpp -Wp,-v` will show you the include paths.

**Comment by abooij** [comment]
Can you confirm this is fixed by 20cd78a?

**Comment by cocreature** [comment]
I can, thanks for looking into this!
